# Simple workflow for Pandoc generation and deployment of static content to GitHub Pages
name: Pandoc generate and deploy HTML/PDF docs to OASIS Github Pages site

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          mkdir output
      - name: Pandoc HTML generation 
        uses: docker://cdang/pandoc-plantuml
        with:
          args: >-
            -f gfm+definition_lists 
            -t html
            -c styles/markdown-styles-v1.7.3a.css 
            --standalone
            --lua-filter pandoc/diagram.lua
            --embed-resources
            --metadata title="Attribute-Centric Authorization Language 1.0"
            --output output/acal-v1.0-draft.html 
            acal-v1.0.md 
      - name: Pandoc PDF generation 
        uses: docker://cdang/pandoc-plantuml
        with:
          args: >-
            -f gfm+definition_lists 
            -t pdf
            -c styles/markdown-styles-v1.7.3a.css
            -H pandoc/custom_latex_header_for_pandoc_pdf_output.tex
            --standalone
            --lua-filter pandoc/diagram.lua
            --embed-resources
            --metadata title="Attribute-Centric Authorization Language 1.0"
            --output output/acal-v1.0-draft.pdf 
            acal-v1.0.md 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload output folder
          path: 'output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: summary
        run: |
          echo "### Check the results: https://oasis-tcs.github.io/xacml-spec/acal-v1.0-draft.html | https://oasis-tcs.github.io/xacml-spec/acal-v1.0-draft.pdf" >> $GITHUB_STEP_SUMMARY

